import { App, TerraformStack, TerraformHclModule, TerraformOutput } from 'cdktf';
import { LocalProvider } from '@cdktf/provider-local/lib/provider';
import { Construct } from 'constructs';

/**
 * Example demonstrating how CDKTF can import and use the HCL module it generated
 * This completes the full circle: CDKTF → HCL Module → Import back to CDKTF
 */
class ImportHclModuleStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new LocalProvider(this, 'local');

    // Import the HCL module generated by CDKTF
    const htmlModule = new TerraformHclModule(this, 'html-module', {
      source: '../cdktf.out/stacks/SimpleTestStack',
      variables: {
        filename: './output/cdktf-import-demo.html',
        title: 'CDKTF Importing HCL Module',
        message: 'This HTML was created by CDKTF importing and using the HCL module! This completes the full circle: CDKTF → HCL Module → Import back to CDKTF.',
      },
    });

    new TerraformOutput(this, 'imported-file', {
      value: htmlModule.get('created_file'),
      description: 'Path to the file created by the imported module',
    });
  }
}

const app = new App({
  context: {
    cdktfRelativeModules: ['../cdktf.out/stacks/SimpleTestStack'],
  },
});
new ImportHclModuleStack(app, 'ImportHclModuleStack');
app.synth();

