# Example: Using the CDKTF-generated module
# This file demonstrates how to use the generated module in a real Terraform configuration

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# Use the module generated by CDKTF
module "html_page" {
  source = "../cdktf.out/stacks/SimpleTestStack"

  filename = "./output/demo.html"
  title    = "CDKTF Generated Module Demo"
  message  = "This HTML file was created by calling a module that was generated from CDKTF TypeScript code!"
}

# Output the result
output "created_file" {
  value       = module.html_page.created_file
  description = "Path to the created HTML file"
}

